### ISSUE TITLE
点击链接后，链接处于白色状态

### ISSUE THREAD

**Issue by mengguang** [newswap/newswap-web#10]
firefox，chrome都可以复现。点开链接后，链接就是一片白色。

<img width="418" alt="newswap-org-bug" src="https://user-images.githubusercontent.com/460748/94337800-cc822700-001f-11eb-85ee-5cbeb4455b82.png">

**Comment by arisac** [comment]
blink & gecko 从 webkit 分家后一些新特性的渲染支持不完整
未来版本中有修复，现有 stable 版本不支持
这个问题体现在 focus 状态下的点击触发操作后，返回原状态的动画部分未渲染完成就停掉了…… 需要点击其他地方去掉 focus 状态才可以……
暂时去掉 focus 状态
